name: Basic JUnit and Endpoint tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'backend/src/**'
      - 'frontend/src/**'
      - 'scratch_tests/**'
      - '**/*.java'
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.properties'

jobs:
  junittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npx npm ci

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run all JUnit tests
        run: ./gradlew test --info --stacktrace

  httptest:
    needs: [ junittest ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npx npm ci

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Verify HTTP tests exist
        run: test -f ./scratch_tests/flow_test.http || (echo "scratch_tests/flow_test.http missing" && exit 1)

      - name: Set up Node.js (for httpyac)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install httpyac and wait-on
        run: npm install -g httpyac wait-on

      - name: Run app in background
        run: nohup ./gradlew bootRun --args="--server.port=8080 --spring.profiles.active=test" > app.log 2>&1 &

      - name: Wait for app (60s)
        run: npx wait-on --timeout 60000 http://localhost:8080/

      - name: Run endpoint tests with httpyac
        env:
          HTTPYAC_NO_PROMPT: "true"
        run: httpyac ./scratch_tests/flow_test.http --all --bail --verbose

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true